-- Migration 083: Add Missing Donna AI System Tables
-- This migration adds critical tables for Donna Terminal functionality

-- ============================================================================
-- 1. DONNA INSIGHTS TABLE
-- ============================================================================
-- Stores real-time insights generated by Donna for enterprise users
CREATE TABLE donna_insights (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    enterprise_id UUID REFERENCES enterprises(id) ON DELETE CASCADE,
    title VARCHAR(255),
    description TEXT,
    content TEXT,
    category VARCHAR(100),
    confidence DECIMAL(3,2) DEFAULT 0.5 CHECK (confidence >= 0 AND confidence <= 1),
    priority VARCHAR(50) DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    actionable BOOLEAN DEFAULT false,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for donna_insights
CREATE INDEX idx_donna_insights_enterprise ON donna_insights(enterprise_id);
CREATE INDEX idx_donna_insights_category ON donna_insights(category);
CREATE INDEX idx_donna_insights_priority ON donna_insights(priority);
CREATE INDEX idx_donna_insights_created ON donna_insights(created_at DESC);
CREATE INDEX idx_donna_insights_actionable ON donna_insights(actionable) WHERE actionable = true;

-- RLS for donna_insights
ALTER TABLE donna_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their enterprise insights" ON donna_insights
    FOR SELECT USING (enterprise_id = public.current_user_enterprise_id());

CREATE POLICY "Service role can insert insights" ON donna_insights
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Service role can update insights" ON donna_insights
    FOR UPDATE USING (true);

CREATE POLICY "Service role can delete insights" ON donna_insights
    FOR DELETE USING (true);

-- ============================================================================
-- 2. DONNA QUERY LOGS TABLE
-- ============================================================================
-- Tracks all Donna query interactions for analytics and feedback
CREATE TABLE donna_query_logs (
    id VARCHAR(255) PRIMARY KEY,
    query_type VARCHAR(100) NOT NULL,
    query_context JSONB NOT NULL,
    enterprise_id UUID REFERENCES enterprises(id) ON DELETE CASCADE,
    insights_count INTEGER DEFAULT 0,
    recommendations_count INTEGER DEFAULT 0,
    confidence DECIMAL(3,2) DEFAULT 0.5 CHECK (confidence >= 0 AND confidence <= 1),
    feedback_received BOOLEAN DEFAULT false,
    feedback_success BOOLEAN,
    feedback_metrics JSONB,
    user_satisfaction DECIMAL(3,2) CHECK (user_satisfaction IS NULL OR (user_satisfaction >= 0 AND user_satisfaction <= 1)),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for donna_query_logs
CREATE INDEX idx_donna_query_logs_enterprise ON donna_query_logs(enterprise_id);
CREATE INDEX idx_donna_query_logs_type ON donna_query_logs(query_type);
CREATE INDEX idx_donna_query_logs_feedback ON donna_query_logs(feedback_received) WHERE feedback_received = true;
CREATE INDEX idx_donna_query_logs_created ON donna_query_logs(created_at DESC);

-- RLS for donna_query_logs
ALTER TABLE donna_query_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their enterprise query logs" ON donna_query_logs
    FOR SELECT USING (enterprise_id = public.current_user_enterprise_id());

CREATE POLICY "Users can insert query logs for their enterprise" ON donna_query_logs
    FOR INSERT WITH CHECK (enterprise_id = public.current_user_enterprise_id());

CREATE POLICY "Users can update query logs for their enterprise" ON donna_query_logs
    FOR UPDATE USING (enterprise_id = public.current_user_enterprise_id());

-- ============================================================================
-- 3. DONNA ANALYSIS LOGS TABLE
-- ============================================================================
-- Stores analysis execution logs for metrics and monitoring
CREATE TABLE donna_analysis_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    query_type VARCHAR(100) NOT NULL,
    query_context JSONB NOT NULL,
    insights_generated INTEGER DEFAULT 0,
    confidence DECIMAL(3,2) DEFAULT 0.5 CHECK (confidence >= 0 AND confidence <= 1),
    enterprise_id UUID REFERENCES enterprises(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for donna_analysis_logs
CREATE INDEX idx_donna_analysis_logs_enterprise ON donna_analysis_logs(enterprise_id);
CREATE INDEX idx_donna_analysis_logs_type ON donna_analysis_logs(query_type);
CREATE INDEX idx_donna_analysis_logs_created ON donna_analysis_logs(created_at DESC);

-- RLS for donna_analysis_logs
ALTER TABLE donna_analysis_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their enterprise analysis logs" ON donna_analysis_logs
    FOR SELECT USING (enterprise_id = public.current_user_enterprise_id());

CREATE POLICY "Service role can insert analysis logs" ON donna_analysis_logs
    FOR INSERT WITH CHECK (true);

-- ============================================================================
-- 4. GRANT PERMISSIONS
-- ============================================================================
GRANT SELECT, INSERT, UPDATE ON donna_insights TO authenticated;
GRANT SELECT, INSERT, UPDATE ON donna_query_logs TO authenticated;
GRANT SELECT, INSERT ON donna_analysis_logs TO authenticated;

-- Service role needs full access for Donna operations
GRANT ALL ON donna_insights TO service_role;
GRANT ALL ON donna_query_logs TO service_role;
GRANT ALL ON donna_analysis_logs TO service_role;

-- ============================================================================
-- 5. HELPER FUNCTIONS
-- ============================================================================

-- Function to get Donna's learning progress
CREATE OR REPLACE FUNCTION get_donna_learning_progress()
RETURNS TABLE (
    total_patterns INTEGER,
    avg_confidence DECIMAL,
    total_best_practices INTEGER,
    avg_success_rate DECIMAL,
    total_queries INTEGER,
    feedback_rate DECIMAL
) AS $$
BEGIN
    RETURN QUERY
    WITH pattern_stats AS (
        SELECT
            COUNT(*)::INTEGER as pattern_count,
            AVG(confidence)::DECIMAL as avg_conf
        FROM donna_patterns
    ),
    practice_stats AS (
        SELECT
            COUNT(*)::INTEGER as practice_count,
            AVG(success_rate)::DECIMAL as avg_success
        FROM donna_best_practices
    ),
    query_stats AS (
        SELECT
            COUNT(*)::INTEGER as query_count,
            SUM(CASE WHEN feedback_received THEN 1 ELSE 0 END)::DECIMAL /
                NULLIF(COUNT(*)::DECIMAL, 0) as feedback_rate
        FROM donna_query_logs
    )
    SELECT
        COALESCE(ps.pattern_count, 0),
        COALESCE(ps.avg_conf, 0),
        COALESCE(pr.practice_count, 0),
        COALESCE(pr.avg_success, 0),
        COALESCE(qs.query_count, 0),
        COALESCE(qs.feedback_rate, 0)
    FROM pattern_stats ps
    CROSS JOIN practice_stats pr
    CROSS JOIN query_stats qs;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Function to get enterprise-specific Donna insights
CREATE OR REPLACE FUNCTION get_enterprise_donna_insights(p_enterprise_id UUID)
RETURNS TABLE (
    insight_type VARCHAR,
    insight_data JSONB,
    confidence DECIMAL,
    created_at TIMESTAMP WITH TIME ZONE
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        'query_pattern'::VARCHAR as insight_type,
        jsonb_build_object(
            'most_common_queries',
            (SELECT jsonb_agg(jsonb_build_object('type', query_type, 'count', query_count))
             FROM (
                SELECT query_type, COUNT(*) as query_count
                FROM donna_query_logs
                WHERE enterprise_id = p_enterprise_id
                GROUP BY query_type
                ORDER BY query_count DESC
                LIMIT 5
             ) top_queries),
            'avg_confidence',
            (SELECT AVG(confidence) FROM donna_query_logs WHERE enterprise_id = p_enterprise_id),
            'feedback_rate',
            (SELECT SUM(CASE WHEN feedback_received THEN 1 ELSE 0 END)::DECIMAL /
                    NULLIF(COUNT(*)::DECIMAL, 0)
             FROM donna_query_logs WHERE enterprise_id = p_enterprise_id)
        ) as insight_data,
        0.8::DECIMAL as confidence,
        NOW() as created_at
    UNION ALL
    SELECT
        'applicable_best_practices'::VARCHAR as insight_type,
        jsonb_build_object(
            'practices',
            (SELECT jsonb_agg(jsonb_build_object(
                'title', title,
                'success_rate', success_rate,
                'usage_count', usage_count
            ))
             FROM donna_best_practices
             WHERE (industry = (SELECT industry FROM enterprises WHERE id = p_enterprise_id)
                    OR industry IS NULL)
             ORDER BY success_rate DESC
             LIMIT 3)
        ) as insight_data,
        0.9::DECIMAL as confidence,
        NOW() as created_at;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Grant execute permissions
GRANT EXECUTE ON FUNCTION get_donna_learning_progress() TO authenticated;
GRANT EXECUTE ON FUNCTION get_enterprise_donna_insights(UUID) TO authenticated;

-- ============================================================================
-- 6. UPDATED_AT TRIGGERS
-- ============================================================================

-- Trigger for donna_insights
CREATE TRIGGER update_donna_insights_updated_at
    BEFORE UPDATE ON donna_insights
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Trigger for donna_query_logs
CREATE TRIGGER update_donna_query_logs_updated_at
    BEFORE UPDATE ON donna_query_logs
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE donna_insights IS 'Real-time insights generated by Donna AI for enterprise users';
COMMENT ON TABLE donna_query_logs IS 'Logs all Donna query interactions for analytics and feedback tracking';
COMMENT ON TABLE donna_analysis_logs IS 'Stores analysis execution logs for Donna system monitoring';

COMMENT ON COLUMN donna_insights.priority IS 'Priority level: low, medium, high, critical';
COMMENT ON COLUMN donna_insights.actionable IS 'Whether the insight has actionable recommendations';
COMMENT ON COLUMN donna_insights.metadata IS 'Additional metadata for the insight';

COMMENT ON COLUMN donna_query_logs.query_type IS 'Type of query: vendor_optimization, contract_strategy, cost_optimization, etc.';
COMMENT ON COLUMN donna_query_logs.feedback_received IS 'Whether user provided feedback on the query results';
COMMENT ON COLUMN donna_query_logs.user_satisfaction IS 'User satisfaction score (0-1)';

COMMENT ON FUNCTION get_donna_learning_progress() IS 'Returns overall Donna AI learning progress metrics';
COMMENT ON FUNCTION get_enterprise_donna_insights(UUID) IS 'Returns enterprise-specific insights and patterns from Donna AI';
